//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hugoAuto1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\J\\Documents\\GitHub\\cornBlog-bootstraptheme")]
        public string source {
            get {
                return ((string)(this["source"]));
            }
            set {
                this["source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\J\\Documents\\GitHub\\cornradio.github.io\\hugo")]
        public string output {
            get {
                return ((string)(this["output"]));
            }
            set {
                this["output"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\J\\Documents\\GitHub\\cornBlog-bootstraptheme\\content\\zh-cn\\posts")]
        public string articles {
            get {
                return ((string)(this["articles"]));
            }
            set {
                this["articles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Google\\Chrome\\Application\\Chrome.exe")]
        public string chromeCommand {
            get {
                return ((string)(this["chromeCommand"]));
            }
            set {
                this["chromeCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\J\\AppData\\Local\\Programs\\Typora\\Typora.exe")]
        public string typoraCommand {
            get {
                return ((string)(this["typoraCommand"]));
            }
            set {
                this["typoraCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\J\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe")]
        public string vscCommand {
            get {
                return ((string)(this["vscCommand"]));
            }
            set {
                this["vscCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\J\\AppData\\Local\\GitHubDesktop\\GitHubDesktop.exe")]
        public string githubCommand {
            get {
                return ((string)(this["githubCommand"]));
            }
            set {
                this["githubCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hugo-theme-bootstrap")]
        public string hugotheme {
            get {
                return ((string)(this["hugotheme"]));
            }
            set {
                this["hugotheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cd C:\\Users\\J\\Documents\\GitHub\\cornradio.github.io\r\ngit pull\r\n\r\ncd C:\\Users\\J\\Doc" +
            "uments\\GitHub\\cornBlog-bootstraptheme\r\ngit pull")]
        public string gitpull_cmd {
            get {
                return ((string)(this["gitpull_cmd"]));
            }
            set {
                this["gitpull_cmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cd C:\\Users\\J\\Documents\\GitHub\\cornradio.github.io\r\ngit add .\r\ngit commit -m \"aut" +
            "o commit\" --verbose\r\ngit push\r\n\r\ncd C:\\Users\\J\\Documents\\GitHub\\cornBlog-bootstr" +
            "aptheme\r\ngit add .\r\ngit commit -m \"auto commit\" --verbose\r\ngit push")]
        public string gitpush_cmd {
            get {
                return ((string)(this["gitpush_cmd"]));
            }
            set {
                this["gitpush_cmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("set http_proxy=http://127.0.0.1:7890 & set https_proxy=http://127.0.0.1:7890\r\ngit" +
            " config http.version HTTP/1.1")]
        public string gitproxy_cmd {
            get {
                return ((string)(this["gitproxy_cmd"]));
            }
            set {
                this["gitproxy_cmd"] = value;
            }
        }
    }
}
